development:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: test_app_development
  pool: 5
  username: root
  host: localhost

test:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: test_app_test
  pool: 5
  username: root
  host: localhost

production:
  adapter: sqlite3
  encoding: utf8
  reconnect: false
  database: test_app_production
  pool: 5
  username: root
  host: localhost